### ISSUE TITLE
UnsatisfiedLinkError: Native method not found: 

### ISSUE THREAD

**Issue by reidash** [madhur/android-chat-bubbles#1]
Hi,

Please advise on this issue, your help will be greatly appreciated.
I keep getting this error even though i added the jniLibs to my project

 Error loading imagejava.lang.UnsatisfiedLinkError: Native method not found: hopon.com.hopon.AndroidUtilities.loadBitmap:(Ljava/lang/String;Landroid/graphics/Bitmap;IIII)V

**Comment by reidash** [comment]
I found out how to solve this issue.
- you are using a native lib and therefore if anyone tries to implement your code, they will have to recompile the jni library with their app package name in the C file

**Comment by madhur** [comment]
:+1:

**Comment by remon** [comment]
@reidash  , would you  mind helping me I am facing the same issue 
how to compile the jni library 
I download the ndk-build 
I used this command inside my app root 

C:\Downloads\Software\android-ndk\ndk-build 

no errors and .so file generated 

emojiicons not shown and the same error I find now (error loading image and native method not found )

**Comment by madhur** [comment]
@remon make sure you `recompile the jni library with their app package name in the C file`

**Comment by 1Dev11** [comment]
i Don't under Stand, can you tell me steps ,  In which  File i have to change and how to recompile it

**Comment by 1Dev11** [comment]
@reidash 
i Don't under Stand, can you tell me steps , In which File i have to change and how to recompile it
