### ISSUE TITLE
What is libchat.so?

### ISSUE THREAD

**Issue by ajnsit** [madhur/android-chat-bubbles#2]
Hi,

The sample project includes a native library called libchat.so which has no description or sources. What does the library do? Are the sources for that library publicly available?

**Comment by madhur** [comment]
Its a native library for rendering emoji bitmaps. All sources are present.

Check out this folder
https://github.com/madhur/android-chat-starter/tree/master/app/jni

You will need NDK to build this JNI sources, through pre-compiled are present in the lib folder.

**Comment by RahulEngEncap** [comment]
Hi sir what is the server u have used in chat-starter and how to give connections...........please help me i have almost stuck in this from last one week...........thank u in advance...:)
