### ISSUE TITLE
How can I compile JNI files inside your library?

### ISSUE THREAD

**Issue by meness** [madhur/android-chat-bubbles#4]
Hi,

I found because of NDK, I couldn't run your library, and now I have installed the NDK but I don't know how to compile your project into my project. How can I do that? Thanks.

**Comment by madhur** [comment]
You can use the simple `ndk-build` to compile. There are pre compiled files in the `lib` directory

**Comment by meness** [comment]
@madhur Thanks for your reply. I've pasted all your jni folder contents to `C:\Users\aessh\AppData\Local\Android\android-ndk-r10` path (my NDK path). and I entered following line in CMD.

`ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Android.mk`

But I got following errors:

```
[armeabi] Compile thumb  : chat.4 <= utils.c
[armeabi] Compile thumb  : chat.4 <= image.c
././image.c:193:27: error: field 'pub' has incomplete type
././image.c: In function 'METHODDEF':
././image.c:200:1: error: expected declaration specifiers before 'my_error_exit'

././image.c:208:1: error: expected declaration specifiers before '__attribute__'

././image.c:239:1: error: expected declaration specifiers before '__attribute__'

././image.c:329:1: error: expected '{' at end of input
make.exe: *** [obj/local/armeabi/objs/chat.4/./image.o] Error 1
```

Can you please teach me how to do it well? I really need to learn this quickly because of my current project. instead, If you give me favor to recompile them with my package name.

**Comment by alirezaaa** [comment]
@madhur I successfully compiled the files but the icons won't show up. why this happens?

**Comment by meness** [comment]
I successfully recompiled the libs and the icons shown up now. If someone tried but couldn't figured out, let me know to help him/her. Thanks @madhur for writing this library. please keep improve it. Thanks again.

**Comment by madhur** [comment]
:+1:  Thanks for the feedback. If you have any improvements, pull requests are welcome.

**Comment by remon** [comment]
@alirezaaa , Images not shown for me too , 

 No implementation found for native AndroidUtilities;.loadBitmap:

this error is also shown with error loading image , however ndk-build  worked fine with me

**Comment by meness** [comment]
@remon Follow these steps:
1) Install NDK
2) Place `jni` folder to your app folder root
3) Open `image.c` file from the `jni` folder
4) Search for `JNIEXPORT` keyword (the file has two occurrences)
5) [IMPORTANT STEP] Move your mouse over the undefined native `loadBitmap` method in the `AndroidUtilities.java` and copy the given name (*)
6) Replace the name with the name followed by `JNIEXPORT` (after `void` keyword)
7) Open CMD
8) Type `cd path_to_app_root` and press Enter
9) Type `path_to_installed_ndk\ndk-build NDK_APPLICATION_MK=jni/Application.mk APP_BUILD_SCRIPT=jni/Android.mk` and press Enter.

If building finished successfully, you're done and emotion icons will be shown.

*: The given name is something like this: `Java_X_AndroidUtilities_loadBitmap` which X is the path to the `AndroidUtilities` class.

**Comment by remon** [comment]
@alirezaaa  , thanks a lot man , you saved my life 

adding also 

```
sourceSets.main {
    jniLibs.srcDir 'libs'
    jni.srcDirs = [] //disable automatic ndk-build call
}
```

to build.gradle made it done with success .

small problem I found now , that the list view don't resize when keyboard open ,how can I make it re sized

**Comment by meness** [comment]
@remon You're welcome. Yes, you should add those lines too because `jniLibs.srcDir 'libs'` makes the JNI default folder to your libs folder.

For solving the problem, you must add `android:windowSoftInputMode="adjustResize"` to the activity in your manifest file. When you add this property, the problem must be solved, but a minor problem will be raised which is re-sizing the chat activity background. To solve that, you should remove the background property from the view group and add it programmatically to the window as I did:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    checkIfOrientationChanged(getResources().getConfiguration());
}

@Override
public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
    checkIfOrientationChanged(newConfig);
}

private void checkIfOrientationChanged(Configuration configuration) {
    if (configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
        getWindow().setBackgroundDrawable(getResources().getDrawable(R.drawable.chat_background_landscape));
    } else if (configuration.orientation == Configuration.ORIENTATION_PORTRAIT) {
        getWindow().setBackgroundDrawable(getResources().getDrawable(R.drawable.chat_background_portrait));
    }
}
```

For better result, add `android:configChanges="orientation|screenSize"` to the chat activity in your manifest file.

**Comment by remon** [comment]
@alirezaaa , I hope you can help me with this issue 

https://github.com/madhur/android-chat-starter/issues/6

**Comment by rahulcn** [comment]
+1 @alirezaaa

**Comment by edwardc1** [comment]
@alirezaaa You are genious!!! You save my life, love you!

**Comment by ghost** [comment]
@meNESS 
I Follow these steps
in this project:

1) Install NDK :+1:
2) Open CMD :+1:
3) Type `cd path_to_app_root`and press Enter :+1:
4) Type `path_to_installed_ndk\ndk-build NDK_APPLICATION_MK=jni/Application.mk APP_BUILD_SCRIPT=jni/Android.mk` and press Enter. :+1:

Genymotion 4.1.1 (x84 arch):
If I click on the button of smiles: 
app crash :grin: and I got an error :scream: in @madhur app:

![4](https://cloud.githubusercontent.com/assets/5690172/15673124/bf75a30a-275e-11e6-9266-139af994cd4e.png)

or

![5](https://cloud.githubusercontent.com/assets/5690172/15680960/c25e6bf6-2781-11e6-9d55-c45e831e2c29.png)

if I run on Samsung galaxy S3 (arm-v7, android 6.0.1), the emoticons button is not pressed, but if  I insert a smiley keyboard and send them - they are shown

I did not change the files.

Sorry for my bad english :new_moon_with_face:

**Comment by niteshvuliv** [comment]
Hi guys,

I have successfully compiled the jni files and I have the .so files. However, I am getting this exception:

    /data/data/<mypackage>/files/lib/libchat.4loc.so" is 32-bit instead of 64-bit

I believe its because the .so files are 32 bit.

How can I create 64-bit .so files?

@meness I followed your steps to compile jni files. Please help me out with this problem.

**Comment by meness** [comment]
@niteshvuliv I think [this link](https://github.com/realm/realm-java/issues/2507) could help

**Comment by niteshvuliv** [comment]
@meness Thanks for the help. I already resolved the issue by excluding 64 bit so files and using only 32 bit so files.

Is it not possible to create 64 bit so files of this project's JNI files for emoji?
